name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      vcpkgResponseFile: ${{github.workspace}}/github-actions/vcpkg.txt

    steps:
    - uses: actions/checkout@v2

    - name: Download vcpkg
      uses: actions/checkout@v2
      with:
        repository: "microsoft/vcpkg"
        ref: "1be75a28bfce2084bb0b59ec92a6853f13d7be66"
        fetch-depth: 1
        path: ${{github.workspace}}/vcpkg

    - name: Cache vcpkg artifacts
      uses: actions/cache@v1
      with:
        path: ${{github.workspace}}/vcpkg
        key: ${{hashFiles(env.vcpkgResponseFile)}}-${{hashFiles('.git/modules/vcpkg/HEAD')}}-${{runner.os}}

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v0
      id: runvcpkg
      with:
        vcpkgArguments: "@${{env.vcpkgResponseFile}}"
        vcpkgDirectory: "${{github.workspace}}/vcpkg/"

    - name: Run CMake with Ninja
      uses: lukka/run-cmake@v0
      id: runcmake
      with:
        cmakeGenerator: Ninja
        cmakeListsTxtPath: "${{github.workspace}}/cmakelists.txt"
        buildWithCMakeArgs: "-- -v"
        buildDirectory: "${{runner.workspace}}/build/"
        useVcpkgToolchainFile: true
        
    - name: Print output of run-vcpkg's task
      run: echo "root='${{steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT}}', triplet='${{steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT}}' "
      
    - name: Clean vcpkg artifact that must not be cached
      run: |
        rm -rfv ${{github.workspace}}/vcpkg/buildtrees
        rm -rfv ${{github.workspace}}/vcpkg/packages
        rm -rfv ${{github.workspace}}/vcpkg/downloads
      shell: bash
        
    - name: Run code
      working-directory: "${{runner.workspace}}/build/"
      run: "${{runner.workspace}}/build/HelloWorld"
