name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run CMake+Ninja without triplet
      uses: lukka/run-cmake@v0
      id: runcmake
      with:
        cmakeGenerator: Ninja
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        buildWithCMakeArgs: "-- -v"
        buildDirectory: "${{runner.workspace}}/build/"
    - name: Run code
      working-directory: "${{runner.workspace}}/build/"
      run: HelloWorld
    #- name: Run unit tests
    #  working-directory: "${{runner.workspace}}/build/projects/render_core/tests/unit/"
    #  run: RenderCoreUnitTests
    #- name: Run regression tests
    #  working-directory: "${{runner.workspace}}/build/projects/render_core/tests/regression/"
    #  run: RenderCoreRegressionTests
