name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run CMake+Ninja wihtout triplet
      uses: lukka/run-cmake@dev
      id: runcmake
      with:
        cmakeGenerator: Ninja
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        buildWithCMakeArgs: "-- -v"
        buildDirectory: "${{runner.worksapce}}/build/"
